
const products = [
    {
      id: 0,
      name: "Iphone 11",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "iphone",
      price: 2999.99,
      image: "./images/iphone-11.png",
      sale: true,
      saleAmount: 200,
    },
    {
      id: 1,
      name: "Iphone 13",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "iphone",
      price: 5200.5,
      image: "./images/iphone-13.png",
    },
    {
      id: 2,
      name: "Iphone 12",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "iphone",
      price: 4444.44,
      image: "./images/Iphone-12.png",
      sale: true,
      saleAmount: 451,
    },
    {
      id: 3,
      name: "Huawei p50 pro",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "huawei",
      price: 1330,
      image: "./images/huawei-2.png",
    },
    {
      id: 4,
      name: "Huawei p20 lite",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "huawei",
      price: 2250,
      image: "./images/huawei-1.png",
    },
    {
      id: 5,
      name: "Nokia c300",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "nokia",
      price: 950.65,
      image: "./images/Nokia.png",
      sale: true,
      saleAmount: 250,
    },
    {
      id: 6,
      name: "Nokia n70",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "nokia",
      price: 690,
      image: "./images/Nokia-2.png",
    },
    {
      id: 7,
      name: "Samsung a53",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "samsung",
      price: 1440,
      image: "./images/Samsung-a53.png",
    },
    {
      id: 8,
      name: "Samsung s20",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "samsung",
      price: 2620.25,
      image: "./images/Samsung-s20.png",
      sale: true,
      saleAmount: 300,
    },
    {
      id: 9,
      name: "Samsung s22",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "samsung",
      price: 3399.99,
      image: "./images/Samsung-s22.png",
    },
    {
      id: 10,
      name: "Samsung s22",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "samsung",
      price: 3495.99,
      image: "./images/Samsung-Galaxy-A2.jpg",
      sale: true,
      saleAmount: 250,
    },
    {
      id: 11,
      name: "Asus Zenfone 10 5G",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "asus",
      price: 1896.99,
      image: "./images/zenfone10.jpg",
    },
    {
      id: 12,
      name: "Asus Zenfone 8",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "asus",
      price: 2958.99,
      image: "./images/zenfone.png",
      sale: true,
      saleAmount: 400
    },
    {
      id: 13,
      name: "Asus ROG Phone 6 Pro",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "asus",
      price: 2285.99,
      image: "./images/Asus_ROG.jpg",
      saleAmount: 800,
    },
    {
      id: 14,
      name: "POCO X3 Pro 5G",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "xiaomi",
      price: 3399.99,
      image: "./images/xiaomi_poco_x3.jpg",
    },
    {
      id: 15,
      name: "Xiaomi Mi 12",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "xiaomi",
      price: 3547.99,
      image: "./images/xiaomimi-12.jpg",
    },
    {
      id: 16,
      name: "Xiaomi Mi 11 Pro",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "xiaomi",
      price: 2399.99,
      image: "./images/xiaomimi-11pro.jpg",
      sale: true,
      saleAmount: 300
    },
  ];
  
  export default products;
